name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]  # test on both LTS lines
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'              # automatic npm cache

      - run: npm ci
      - run: npm run build         # compiles with tsup
      - run: npm run typecheck     # runs type checking
      - run: npm test              # runs jest
      - run: npm run lint          # runs eslint
